// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrmRox-EfJsHnhEHEp9tmt-feAwm1Qbtk',
    appId: '1:593746663874:web:e7ee57c61ce248a8c09e5b',
    messagingSenderId: '593746663874',
    projectId: 'integrakidsapp',
    authDomain: 'integrakidsapp.firebaseapp.com',
    storageBucket: 'integrakidsapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQUEUUfVIuWHwz56807vfiavJWsvQeL5U',
    appId: '1:593746663874:android:f5970dd1d2ea1906c09e5b',
    messagingSenderId: '593746663874',
    projectId: 'integrakidsapp',
    storageBucket: 'integrakidsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqTdeOTjcv-BLVN2A1vMvDSKI9ZuAEGAo',
    appId: '1:593746663874:ios:b78d5a351133d140c09e5b',
    messagingSenderId: '593746663874',
    projectId: 'integrakidsapp',
    storageBucket: 'integrakidsapp.appspot.com',
    iosBundleId: 'com.example.integrakidsApp',
  );
}
